import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import RootLayoutClient from "./components/layout/RootLayoutClient";
import { Provider } from "react-redux";
import { store } from "./redux/store/store";
import { Providers } from "./components/common/ReduxProvider";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Admin eComm App with Next.js,MUI,Typescript",

  description: "Generated by Julnar Nabeel",
};

export default function RootLayout({
  children,
}: 

Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Providers>
            <RootLayoutClient>{children}</RootLayoutClient>
            </Providers>
      </body>
    </html>
  );
}
